#
###################################
# Site wide configuration
####################################
#
title:       "RainbowColors's blog"
description: '好好学习,天天向上.'
url:         #

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: RainbowColors
  avatar: avatar.png
  job: " iOS & JS Developer"
  bio: "嗨,你好。我是彩虹,一名来自中国·上海的iOS开发者。"
  email: devsonw@gmail.com
  disqus-shortname: RainbowColorsblog
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: #analytics
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: devsonw #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
